env:
    browser: true
    es6: true
    webextensions: true
extends: "eslint:recommended"
parserOptions:
    ecmaVersion: 2018
    sourceType: module
rules:
    accessor-pairs: error
    array-bracket-newline: error
    array-bracket-spacing: error
    array-callback-return: error
    array-element-newline:
        - error
        - multiline: true
    arrow-body-style:
        - error
        - as-needed
    arrow-parens:
        - error
        - as-needed
        - requireForBlockBody: true
    arrow-spacing: error
    block-scoped-var: error
    block-spacing: error
    brace-style:
        - error
        - 1tbs
    camelcase: error
    capitalized-comments:
        - error
        - always
        - ignoreConsecutiveComments: true
    class-methods-use-this: error
    comma-dangle:
        - error
        - arrays: always-multiline
          objects: always-multiline
          imports: always-multiline
          exports: always-multiline
          functions: always-multiline
    comma-spacing: error
    comma-style: error
    complexity: error
    computed-property-spacing: error
    consistent-return: error
    consistent-this:
        - error
        - self
    curly:
        - error
        - multi-or-nest
        - consistent
    default-case: error
    default-case-last: error
    default-param-last: error
    dot-location:
        - error
        - property
    dot-notation: error
    eol-last: error
    eqeqeq: error
    func-call-spacing: error
    func-name-matching: error
    func-names:
        - error
        - as-needed
    func-style:
        - error
        - declaration
        - allowArrowFunctions: true
    function-call-argument-newline:
        - error
        - consistent
    function-paren-newline: error
    generator-star-spacing: error
    guard-for-in: error
    grouped-accessor-pairs:
        - error
        - getBeforeSet
    implicit-arrow-linebreak: error
    indent:
        - error
        - 4
        - SwitchCase: 1
    init-declarations: error
    key-spacing:
        - error
        - singleLine: {}
          multiLine: {}
          align:
              on: value
    keyword-spacing: error
    line-comment-position: error
    linebreak-style: error
    lines-around-comment:
        - error
        - beforeBlockComment: true
          beforeLineComment: true
          allowBlockStart: true
          allowObjectStart: true
          allowArrayStart: true
          allowClassStart: true
    lines-between-class-members:
        - error
        - always
        - exceptAfterSingleLine: true
    max-classes-per-file: error
    max-depth: error
    max-len:
        - error
        - code: 100
    max-lines: error
    max-lines-per-function: error
    max-nested-callbacks:
        - error
        - max: 4
    max-params: error
    max-statements:
        - error
        - max: 30
    max-statements-per-line: error
    multiline-comment-style:
        - error
        - separate-lines
    multiline-ternary:
        - error
        - always-multiline
    new-cap: error
    new-parens: error
    newline-per-chained-call: error
    no-alert: error
    no-array-constructor: error
    no-bitwise: error
    no-caller: error
    no-confusing-arrow: error
    no-constructor-return: error
    no-div-regex: error
    no-duplicate-imports: error
    no-else-return: error
    no-empty-function: error
    no-eq-null: error
    no-eval: error
    no-extend-native: error
    no-extra-bind: error
    no-extra-label: error
    no-extra-parens:
        - error
        - all
        - enforceForArrowConditionals: false
    no-floating-decimal: error
    no-global-assign: error
    no-implicit-coercion: error
    no-implicit-globals: error
    no-implied-eval: error
    no-inline-comments: error
    no-invalid-this: error
    no-iterator: error
    no-label-var: error
    no-labels: error
    no-lone-blocks: error
    no-lonely-if: error
    no-loop-func: error
    no-loss-of-precision: error
    no-magic-numbers:
        - error
        - ignore: [0, 1]
    no-mixed-operators: error
    no-multi-assign: error
    no-multi-spaces: error
    no-multi-str: error
    no-multiple-empty-lines:
        - error
        - max: 1
          maxEOF: 0
          maxBOF: 0
    no-negated-condition: error
    no-nested-ternary: error
    no-new: error
    no-new-func: error
    no-new-object: error
    no-new-wrappers: error
    no-nonoctal-decimal-escape: error
    no-octal-escape: error
    no-param-reassign:
        - error
        - props: true
    no-plusplus: error
    no-promise-executor-return: error
    no-proto: error
    no-prototype-builtins: error
    no-return-assign: error
    no-return-await: error
    no-script-url: error
    no-self-compare: error
    no-sequences: error
    no-shadow:
        - error
        - builtinGlobals: true
          hoist: all
    no-shadow-restricted-names: error
    no-tabs: error
    no-template-curly-in-string: error
    no-throw-literal: error
    no-trailing-spaces: error
    no-undef-init: error
    no-underscore-dangle: error
    no-unmodified-loop-condition: error
    no-unneeded-ternary: error
    no-unsafe-negation: error
    no-unsafe-optional-chaining: error
    no-unused-expressions: error
    no-unused-vars:
        - error
        - vars: all
          varsIgnorePattern: "^_"
          args: all
          argsIgnorePattern: "^_"
          caughtErrors: all
          caughtErrorsIgnorePattern: "^_"
    no-use-before-define: error
    no-useless-backreference: error
    no-useless-call: error
    no-useless-computed-key: error
    no-useless-concat: error
    no-useless-constructor: error
    no-useless-rename: error
    no-useless-return: error
    no-var: error
    no-void: error
    no-warning-comments: warn
    no-whitespace-before-property: error
    no-with: error
    nonblock-statement-body-position: error
    object-curly-newline: error
    object-curly-spacing: error
    object-property-newline:
        - error
        - allowAllPropertiesOnSameLine: true
    object-shorthand:
        - error
        - always
        - avoidExplicitReturnArrows: true
    one-var:
        - error
        - initialized: never
          uninitialized: always
    one-var-declaration-per-line: error
    operator-assignment: error
    operator-linebreak: error
    padded-blocks:
        - error
        - never
    prefer-arrow-callback: error
    prefer-const: error
    prefer-destructuring:
        - error
        - array: true
          object: true
        - enforceForRenamedProperties: true
    prefer-exponentiation-operator: error
    prefer-named-capture-group: error
    prefer-numeric-literals: error
    prefer-object-spread: error
    prefer-promise-reject-errors: error
    prefer-regex-literals: error
    prefer-rest-params: error
    prefer-spread: error
    prefer-template: error
    quote-props:
        - error
        - as-needed
    quotes:
        - error
        - double
    radix: error
    require-atomic-updates: error
    require-await: error
    require-unicode-regexp: error
    rest-spread-spacing: error
    semi: error
    semi-spacing: error
    semi-style: error
    sort-imports: error
    space-before-blocks: error
    space-before-function-paren:
        - error
        - anonymous: always
          named: never
          asyncArrow: always
    space-in-parens: error
    space-infix-ops: error
    space-unary-ops: error
    spaced-comment:
        - error
        - always
        - block:
              balanced: true
    strict:
        - error
        - global
    switch-colon-spacing: error
    symbol-description: error
    template-curly-spacing: error
    template-tag-spacing: error
    unicode-bom: error
    vars-on-top: error
    wrap-iife:
        - error
        - inside
        - functionPrototypeMethods: true
    wrap-regex: error
    yield-star-spacing: error
    yoda: error
